version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: petshop-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: YourStrong!Pass123
      POSTGRES_DB: PetShop
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  petshop-api:
    build:
      context: .
      dockerfile: PetShop.API/Dockerfile
    container_name: petshop-api
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    env_file:
      - .env
    

volumes:
  postgres_data:
